 version: 2
 jobs:
   build:
     docker:
       - image: node:10
     steps:
       - checkout
       - run: echo "Start Building bro!"
       - run:
            command: npm install # install dependencies
       - run:
            command: npm lint # lint your code
       - run:
            command: npm test # run your unit tests
       - run:
            command: npm run chromatic # run your visual tests
